config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'

   resources :users, only: [:show, :index]
    resources :stadiums do
      resources :experiences
    end
      resources :stadiums do
      resources :seats
    end

end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
  belongs_to :stadium

  validates :stadium_id, :name, :rating, :url, :location,
    presence: true

end

app/models/experience.rb
class Experience < ActiveRecord::Base

  belongs_to :stadium
  belongs_to :user

  validates :user_id, :stadium_id, :title, :summary,
  presence: true
  validates :food, :atmosphere, :neighborhood, :fans,
  inclusion: { in: 1..5}
  validates :atmosphere,
  inclusion: { in: 1..5}


  def owner?(current_user)
    user == current_user
  end
end

app/models/seat.rb
class Seat < ActiveRecord::Base

  belongs_to :stadium
  belongs_to :user

  validates :user_id, presence: true
  validates :stadium_id, presence: :true
  validates :section, presence: :true, length: { maximum: 5 }
  validates :row, presence: :true, length: { maximum: 5 }
  validates :seat_number, presence: :true, length: { maximum: 5 }
  validates :seat_description, presence: :true, length: { maximum: 200 }

  def owner?(current_user)
    user == current_user
  end

end

app/models/stadium.rb
class Stadium < ActiveRecord::Base
  has_many :experiences
  has_many :seats

  validates :name,
    presence: true
  validates :city,
    presence: true
  validates :state,
    presence: true
  validates :capacity,
    presence: true
  validates :playing_surface,
    presence: true
  validates :roof_type,
    presence: true
  validates :team,
    presence: true
  validates :year,
    presence: true

    paginates_per 4

  def self.search(query)
    where("state ilike ?", "%#{query}%")
  end

  def top_hotels
    hotels = []
    hotel_results = Yelp.client.search(self.city, { category_filter: 'hotels', sort: 2, limit: 20 })
    hotel_results.businesses.each do |business|
      hotel_hash = {
        name: business.name,
        rating: business.rating,
        url: business.url,
        location: business.location.display_address.join(", "),
        image_url: business.respond_to?(:image_url) ? business.image_url : "https://s3.amazonaws.com/breakabletoy-stadiums/default.jpeg",
        display_phone: business.respond_to?(:display_phone) ? business.phone : "No phone number available"
      }
      hotels << hotel_hash
    end
    hotels.sort_by {|h| h[:rating]}.reverse
  end

  def top_bars
      bars = []
      bar_results = Yelp.client.search(self.city, { category_filter: 'bars', sort: 2, limit: 20 })
      bar_results.businesses.each do |business|
      bar_hash = {
          name: business.name,
          rating: business.rating,
          url: business.url,
          location: business.location.display_address.join(", "),
          image_url: business.respond_to?(:image_url) ? business.image_url : "https://s3.amazonaws.com/breakabletoy-stadiums/default.jpeg",
          display_phone: business.respond_to?(:display_phone) ? business.phone : "No phone number available"
      }
        bars << bar_hash
      end
      bars.sort_by {|h| h[:rating]}.reverse

  end

  def top_attractions
      attractions = []
      attraction_results = Yelp.client.search(self.city, { category_filter: 'arts', sort: 2, limit: 20 })
      attraction_results.businesses.each do |business|
      attraction_hash = {
          name: business.name,
          rating: business.rating,
          url: business.url,
          location: business.location.display_address.join(", "),
          image_url: business.respond_to?(:image_url) ? business.image_url : "https://s3.amazonaws.com/breakabletoy-stadiums/default.jpeg",
          display_phone: business.respond_to?(:display_phone) ? business.phone : "No phone number available"
      }
        attractions << attraction_hash
      end
      attractions.sort_by {|h| h[:rating]}.reverse
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :experiences
  has_many :seats
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  validates :username, uniqueness: true
  validates :username, presence: true, length: { in: (6..32) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ActionController::Base
  before_filter :authenticate_user!

  def new
    @experiences = Experience.new
  end

  def edit
    @experience = Experience.find(params[:id])
    @stadium = Stadium.find(params[:stadium_id])
  end

  def update
    @experience= Experience.find(params[:id])
    if @experience.update(experience_params)
      flash[:notice]= "Experience updated successfully"
      redirect_to stadium_path(params[:stadium_id])
    end
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.stadium_id = params[:stadium_id]
    @experience.user_id = current_user.id


    if @experience.save
      flash[:notice]= "Experience created successfully"
      redirect_to stadium_path(params[:stadium_id])
    else
      flash[:notice]= "You didn't enter enough information."
      redirect_to stadium_path(params[:stadium_id])
    end
  end

  def show
    @experience = Experience.find(params[:id])
    if @experience.destroy
      flash[:notice] = "Experience deleted successfully"
      redirect_to stadium_path(params[:stadium_id])
    end
  end

private

  def experience_params
    params.require(:experience).permit(:title, :summary, :food, :atmosphere, :neighborhood, :fans)
  end

end

app/controllers/seats_controller.rb
class SeatsController < ActionController::Base
  before_filter :authenticate_user!

  def new
    @seats = Seat.new
  end

  def edit
    @seat= Seat.find(params[:id])
    @stadium = Stadium.find(params[:stadium_id])
  end

  def update
    @seat= Seat.find(params[:id])
    if @seat.update(seat_params)
      flash[:notice]= "Seats updated successfully"
      redirect_to stadium_path(params[:stadium_id])
    end
  end

  def create
    @seat = Seat.new(seat_params)
    @seat.stadium_id = params[:stadium_id]
    @seat.user_id = current_user.id
    if @seat.save
      flash[:notice]= "Seat created successfully"
      redirect_to stadium_path(params[:stadium_id])
    else
      flash[:notice]= "You didn't enter enough information."
      render stadium_path(params[:stadium_id])
    end
  end

  def show
    @seat = Seat.find(params[:id])
    if @seat.destroy
      flash[:notice] = "Seat deleted successfully"
      redirect_to stadium_path(params[:stadium_id])
    end
  end


private

  def seat_params
    params.require(:seat).permit(:section, :row, :seat_number, :seat_description)
  end

end

app/controllers/stadiums_controller.rb
class StadiumsController < ApplicationController
  def index
   @stadiums = Stadium.order(name: :asc).page params[:page]

   if params[:search]
      @stadiums = Stadium.search(params[:search]).order("name").page(params[:page])
    else
      Stadium.order("name").page(params[:page])
   end
  end

  def show
    @stadium = Stadium.find(params[:id])
    @experiences = @stadium.experiences.order(created_at: :desc)
    @experience = Experience.new
    @seats = @stadium.seats.order(created_at: :desc)
    @seat = Seat.new
    @hotels = @stadium.top_hotels
    @bars = @stadium.top_bars
    @attractions = @stadium.top_attractions
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     @users =  User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @stadiums = Stadium.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xperience</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>




  <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/stadiums/index.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Xperience", root_path %></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <% if user_signed_in? %>
        <li class="active"><%= link_to "Profile", edit_user_registration_path %></li></li>
        <li class="active"><%= link_to "Sign Out", destroy_user_session_path, data: {method: 'delete'} %>
      <% else %>
        <li class="active"><%= link_to "Sign up", new_user_registration_path %></li>
        <li class="active"><%= link_to "Log In", user_session_path %></li>
      <% end %>
    </ul>
    <ul class="left">
      <li class="active">
       <li>
        <%= form_tag(stadiums_path, :method => "get", id: "search-form") do %>
        <ul>
          <li><%= text_field_tag :search, params[:search], placeholder: "Search Stadiums State" %></li>
          <li><%= submit_tag "Search", class: "button radius" %></li>
        </ul>
        <% end %>
    </ul>
  </section>
</nav>
<div class="row" style="margin-top: 20px">
   <div class="small-8 large-centered columns">
      <% @stadiums.each do |stadium| %>
        <div class="panel">
          <div class="small-7 large-centered columns">
            <%=stadium.name%>
          </div>
          <div class="small-8 large-centered columns">
            <div class="morph pic">
              <%= link_to (image_tag(stadium['photo'])), stadium_path(stadium) %><br>
            </div>
          <div class="small-7 large-centered columns">
            <%=stadium.city%>,<%= stadium.state %><br>
            <%=stadium.team %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= paginate @stadiums %>

app/views/stadiums/show.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Xperience", root_path %></a></h1>
    </li>
    <li class="toggle-topbar icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <% if user_signed_in? %>
        <li class="active"><%= link_to "Profile", edit_user_registration_path %></li>
        <li class="active"><%= link_to "Sign Out", destroy_user_session_path, data: {method: 'delete'} %></li>
      <% else %>
        <li class="active"><%= link_to "Stadiums", stadiums_path %></li>
        <li class="active"><%= link_to "Log In", user_session_path %></li>
      <% end %>
    </ul>
    <ul class="left">
      <li class="active">
       <% if !user_signed_in? %>
        <%= link_to "Sign up", new_user_registration_path %></li>
        <% else %>
        <li class="active"><%= link_to "Stadiums", stadiums_path %></li>
       <% end %>
    </ul>
  </section>
</nav>
<div class="row">
  <div class="small-12 columns">
    <h2>  <%= @stadium.name %> </h2>
      <div>
        <%= image_tag @stadium['photo'], style:"height: 800px; width: 1000px;" %>
      </div>
  </div>
</div> <br>
<div class="row">
  <div class="small-12 columns large-centered columns">
    <dl class="tabs" data-tab>
      <dd class="active"><a href="#panel1">XPeriences</a></dd>
      <dd><a href="#panel2"> Stadium Layout</a></dd>
      <dd><a href="#panel3"> Information</a></dd>
      <dd><a href="#panel4"> Hotels</a></dd>
      <dd><a href="#panel5"> Night Life</a></dd>
      <dd><a href="#panel6"> Attractions</a></dd>
    </dl>
  <div class="tabs-content">
    <div class="content active" id="panel1">
      <div class="panel">
        <h5>Share Your Experience</h5>
          <%= form_for [@stadium, @experience] do |f| %>
            <div><%= f.label :title %><%= f.text_field :title %></div>
            <div><%= f.text_area :summary %></div>
            <div class="large-1"><%= f.label :food %><%= f.select :food, (1..5) %></div>
            <div class="large-1"><%= f.label :atmosphere%><%= f.select :atmosphere, (1..5) %></div>
            <div class="large-1"><%= f.label :neighborhood %><%= f.select :neighborhood, (1..5) %></div>
            <div class="large-1"><%= f.label :fans %><%= f.select :fans, (1..5) %></div>
            <div><%= f.submit "Add Experience", class: "tiny button active nice round" %></div>
          <% end %>
      </div>
        <% @experiences.each do |experience| %>
             <div class="panel">
                <div>
                  <h6><%= experience.summary %></h6>
                  <h6> Food: <%= experience.food %></h6>
                  <h6> Atmosphere: <%= experience.atmosphere%></h6>
                  <h6> Neighborhood: <%= experience.neighborhood %></h6>
                  <h6> Fans: <%= experience.fans %></h6>
                  <% if experience.owner?(current_user) %>
                  <h6 class="tiny button active nice round"> <%= link_to "Delete review", stadium_experience_path(@stadium, experience) %> <h6>
                 <% end %>
                </div>
              </div>
        <% end %>
  </div>
   <div class="content" id="panel2">
     <div class="row">
        <div class="small-10 large-centered columns">
          <div> <%=image_tag @stadium['seating_chart'], style:"height: 600px; width: 800px;" %></div>
          </div>
      </div> <br>
      <div class="row">
      <div class="small-6 large-centered columns">
      <div class="panel">
        <h5>Where did you sit?</h5>
          <%= form_for [@stadium, @seat] do |s| %>
            <div><%= s.label "Section" %><%= s.text_field :section %></div>
            <div><%= s.label "Row" %><%= s.text_field :row %></div>
            <div><%= s.label "Seat Number" %><%= s.text_field :seat_number %></div>
             <div><%= s.label "Tell us about it" %><%= s.text_area :seat_description %></div>
            <div><%= s.submit "Submit", class: "tiny button active nice round" %></div>
          <% end %>
      </div>

       <% @seats.each do |seat| %>
             <div class="panel">
                <div>
                  <h6> Section: <%= seat.section %></h6>
                  <h6> Row: <%= seat.row%></h6>
                  <h6> Seat Number: <%= seat.seat_number %></h6>
                  <h6> Seats Overview: <br> <br><%= seat.seat_description %></h6>
                <% if seat.owner?(current_user) %>
                  <h6 class="tiny button active nice round"> <%= link_to "Delete review", stadium_seat_path(@stadium, seat) %> <h6>
                <% end %>
                </div>
            </div>
        <% end %>
       </div>
      </div>
    </div>
    <div class="content" id="panel3">
      <div class="panel">
        <div> Location: <%=@stadium.city%>, <%=@stadium.state %></div>
        <div>Capacity: <%=(@stadium.capacity)%></div>
        <div>Playing Surface: <%=@stadium.playing_surface %></div>
        <div>Roof Type: <%=@stadium.roof_type%></div>
        <div>Team: <%=@stadium.team %></div>
        <div>Year Opened: <%=@stadium.year %> </div>
      </div>
      <div class="panel"> Description:
        <p><%=@stadium.description %> </p>
      </div>
    </div>
    <div class="content" id="panel4">
      <%@hotels.each do |hotel| %>
      <div class="row">
        <div class="small-6 large-centered columns">
          <div class="panel">
              <%= hotel[:name] %> <br>
              <%= image_tag hotel[:image_url], style: "height: 100px; width: 150px;" %> <br>
              Rating: <%= hotel[:rating] %><br>
              Website: <br> <%= link_to "#{hotel[:url]}", hotel[:url] %><br>
              Address: <%= hotel[:location] %> <br>
              Phone Number: <%= hotel[:display_phone] %>
          </div>
        </div>
      </div>
      <%end%>
    </div>
    <div class="content" id="panel5">
        <%@bars.each do |bar| %>
        <div class="row">
          <div class="small-6 large-centered columns">
            <div class="panel" >
                 <%= bar[:name] %><br>
                 <%= image_tag bar[:image_url], style: "height: 100px; width: 150px;" %> <br>
                 Rating: <%= bar[:rating] %><br>
                 Website: <br> <%= link_to "#{bar[:url]}", bar[:url] %><br>
                 Address: <%= bar[:location] %> <br>
                 Phone Number: <%= bar[:display_phone] %>
            </div>
          </div>
        </div>
      <%end%>
    </div>
    <div class="content" id="panel6">
        <%@attractions.each do |a| %>
          <div class="row">
            <div class="small-6 large-centered columns">
              <div class="panel" >
                <%= a[:name] %><br>
                <%= image_tag a[:image_url], style: "height: 100px; width: 150px;" %> <br>
                Rating: <%= a[:rating] %><br>
                Website: <br> <%= link_to "#{a[:url]}", a[:url] %><br>
                Address: <%= a[:location] %> <br>
                Phone Number: <%= a[:display_phone]%>
              </div>
            </div>
          </div>
      <%end%>
    </div>
 </div>
</div>

app/views/welcome/index.html.erb
<div class="football" >
  <div class="header">
      <h1><%=  "Stadium XPerience's"  %></h1>
      <h2><%= link_to "Enter", stadiums_path %></h2>
  </div>
</div>